blogapplication/blogapplication/urls.py
from django.contrib import admin
from django.urls import path
from Blogs import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/",views.home,name='home'),
    path("",views.welcome),
    path("about/",views.about_page , name="about"),
    path("contact/",views.contact_page , name="contact"),
    path("dashboard/",views.dashboard_page , name="dashboard"),
    path("login/",views.login_page , name="login"),
    path("logout/",views.logout_page , name="logout"),
    path("signup/",views.signup_page , name="signup"),
    path('addpost/',views.addpost,name='addpost'),
    path('updatepost/<id>/',views.updatepost,name='updatepost'),
    path('delete/<id>/',views.delete,name='deletedata'),
]

blogapplication/Blogs/models.py
from django.db import models
class Post(models.Model):
    title=models.CharField(max_length=200);
    author=models.CharField(max_length=100);
    desc=models.TextField();
    def __str__(self):
        return self.title;

blogapplication/Blogs/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Post
class Postform(forms.ModelForm):
    class Meta:
        model=Post;
        fields=['title','author','desc'];
        widgets={'title':forms.TextInput(attrs={'class':'form-control'}),'author':forms.TextInput(attrs={'class':'form-control'}),'desc':forms.Textarea(attrs={'class':'form-control'}),}
class BlogForm(UserCreationForm):
    password1=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2=forms.CharField(label='Confirm Password',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        labels={'email':"EMAIL"}
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
        }

blogapplication/Blogs/views.py
from django.shortcuts import render ,HttpResponseRedirect
from . forms import BlogForm
from .models import Post
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate , login , logout
from .forms import Postform
def home(request):   
    posts=Post.objects.all();
    return render(request,"blog/home.html",{"Post":posts});
def about_page(request):
    return render(request,"blog/about.html");
def contact_page(request):
    return render(request,"blog/contact.html");
def dashboard_page(request):
    if request.user.is_authenticated: 
        posts=Post.objects.all();
        return render(request,"blog/dashboard.html",{"Post":posts});
    else:
        return HttpResponseRedirect("/") 
def welcome(request):
    return render(request,"blog/welcome.html");
def logout_page(request):
    if request.user.is_authenticated: 
        logout(request);
    else:
        return HttpResponseRedirect("/") 
    return HttpResponseRedirect("/");
def signup_page(request):
    if request.method=='POST':
        fm=BlogForm(request.POST);
        if fm.is_valid():
            fm.save();
            return HttpResponseRedirect('/login/');
    else:
        fm=BlogForm();
    return render(request,"blog/signup.html",{"Form":fm});
def login_page(request):
    if request.method=='POST':
        fm=AuthenticationForm(request=request,data=request.POST);
        if fm.is_valid():
            a=fm.cleaned_data['username'];
            b=fm.cleaned_data['password'];
            new_user=authenticate(username=a,password=b);
            if not new_user is None:
                login(request,new_user);
                return HttpResponseRedirect("/home/");
            else:
                return HttpResponseRedirect("/signup/");
    else:
        fm=AuthenticationForm();
    return render(request,"blog/login.html",{"Form":fm});





def addpost(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            fm=Postform(request.POST);
            if fm.is_valid():
                fm.save();
                fm=Postform();
        else:
            fm=Postform();
        return render(request,'blog/addpost.html',{'Form':fm});
    else:
        return HttpResponseRedirect("/login/")
def updatepost(request,id):
    if request.user.is_authenticated:
        data=Post.objects.filter(id=id).first();
        if request.method=='POST':
            fm=Postform(request.POST,instance=data);
            if fm.is_valid():
                fm.save();
                return HttpResponseRedirect('/dashboard/')
        else:
            fm=Postform(instance=data);
            return render(request,'blog/update.html',{"Form":fm});
    else:
        return HttpResponseRedirect("/login/")


def delete(request,id):
    if request.method=='POST':
        data=Post.objects.filter(id=id);
        data.delete();
    return  HttpResponseRedirect("/dashboard/");

blogapplication/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}



<div class="col-sm-10 text-center">
    <h3 class="text-white  text-center" style="margin-top: 80px;" >About </h3>
    <p class="text-white" style="margin-top: 20px;">
        Welcome to our blog application, where words come alive and ideas flourish! 

Our platform is designed to empower writers, thinkers, and storytellers of all kinds to share their passions, knowledge, and creativity with the world. Whether you're a seasoned blogger or just starting out on your writing journey, our user-friendly interface and robust features make it easy to craft compelling content and engage with your audience.

Here, you'll find a diverse community of bloggers spanning various topics, from travel and lifestyle to technology and literature. Explore an endless array of articles, essays, and musings that inspire, educate, and entertain.

Join us in celebrating the power of words and the beauty of expression. Let your voice be heard, your stories be told, and your ideas spark meaningful conversations. Together, we'll build a vibrant community where every voice matters and every story shines. Welcome to our blog application – where the world's stories come together.
    </p>
    <h6 style="margin-top: 20%;"> ©Jatin Kashyap || All Rights Reserved</h6>
</div>

























{% endblock content %}

blogapplication/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}


<div class="col-sm-10">
    <h3 class="text-white my-5" > Dashboard /Add Post</h3>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for fm in Form %}
        <div class="row mb-3">
            <label for="inputEmail3" class="col-sm-2 col-form-label">{{fm.label_tag}} </label>
            <div class="col-sm-10">{{fm}} </div></div>
                          <p style="color: red;" >  {{fm.errors | striptags}} </p> 
        
        {% endfor %}
        <input type="submit" value="ADD POST" class="btn btn-dark form-control"/> 
        <br>
        <br>
        <a href="{% url 'dashboard' %}" class="btn btn-dark form-control" > Cancel</a>
    </form>
</div>
{% endblock content %}

blogapplication/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyBlogs</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
    <style>
        body{
        background-color: black;
        color: antiquewhite;
    }
    .card{
        background-color: rgb(83, 81, 81);
    }
</style>
<div class="container-fluid bg-dark">
    {% include 'blog/navbar.html' %}
</div>
<div  class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block msg %}
            {% endblock msg %}
        </div>
    </div>
    <div class="row">
        {% block side %}
        {% endblock side %}
        
        
        {% block content %}
        {% endblock content %}
    </div>
</div>
<script src="{% static 'blog/js/jquery.js' %}" ></script>
<script src="{% static 'blog/js/popper.js' %}" ></script>
<script src="{% static 'blog/js/bootstrap.js' %}" ></script>
</body>
</html>

blogapplication/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}



<div class="col-sm-10 text-center">
    <h3 class="text-white  text-center" style="margin-top: 80px;" >Contact Us </h3>
    <form class="row g-3">
        <div class="col-md-6">
          <label for="inputEmail4" class="form-label">User Name</label>
          <input type="text" class="form-control" id="inputEmail4" placeholder="Aapka Shubh Naam" >
        </div>
        <div class="col-md-6">
          <label for="inputEmail4" class="form-label" >Email</label>
          <input type="email" class="form-control" id="inputEmail4" placeholder="Aapka Shubh E-Mail Address">
        </div>
        <!-- <div class="col-md-6">
          <label for="inputPassword4" class="form-label">Password</label>
          <input type="password" class="form-control" id="inputPassword4">
        </div> -->
        <div class="col-12">
          <label for="message" class="form-label">Your Words For Us</label>
          <!-- <input type="text-area" class="form-control" id="inputAddress" > -->
          <textarea class="form-control" id="message" rows="3" placeholder="Message"></textarea>
        </div>
        <!-- <div class="col-12">
          <label for="inputAddress2" class="form-label">Address 2</label>
          <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
        </div> -->
        <!-- <div class="col-md-6">
          <label for="inputCity" class="form-label">City</label>
          <input type="text" class="form-control" id="inputCity">
        </div> -->
        <!-- <div class="col-md-4">
          <label for="inputState" class="form-label">State</label>
          <select id="inputState" class="form-select">
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div> -->
        <!-- <div class="col-md-2">
          <label for="inputZip" class="form-label">Zip</label>
          <input type="text" class="form-control" id="inputZip"> -->
        <!-- </div> -->
        <!-- <div class="col-12">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
              Check me out
            </label>
          </div>
        </div> -->
        <div class="col-12">
          <button type="submit" class="btn btn-primary">Send</button>
        </div>
      </form>
</div>

























{% endblock content %}

blogapplication/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}



<div class="col-sm-10 text-center">
    <h3 class="text-white  text-center" style="margin-top: 80px;" >Dashboard </h3>
    <a href="{%  url 'addpost' %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3" >Show Post Information</h4>
    {% if Post %}
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
            {% for i in Post %}
          <tr>
            <th scope="row">{{i.id}}</th>
            <td>{{i.title}}</td>
            <td>{{i.desc}}</td>
            <td class="text-center">
                <a href="{%  url 'updatepost' i.id %}" class="btn btn-warning btn-sm"> Edit</a>
                <br>
                <br>
                {% if perms.blog.delete_post %}
                <form method="post" class="d-inline" action="{%  url 'deletedata' i.id %}">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                </form>
                {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
    <h4 class="text-center alert alert-warning mt-3" >No Information</h4>
    {% endif %}
</div>
























{% endblock content %}

blogapplication/templates/blog/footer.html
<nav class="navbar sticky-bottom bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Sticky bottom</a>
      <p>hekhbhcvhbkhbkjbhkbhb Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nam sapiente sint nesciunt unde dignissimos non laboriosam rem in facilis asperiores, cumque reprehenderit natus consequatur enim adipisci error ab maxime provident.z</p>
    </div>
  </nav>

blogapplication/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10 text-center" >
  <h3 class="text-white  text-center" style="margin-top: 60px;" >Blogs... </h3>
  {% for i in Post %}
    <div class="card">
      <div class="card-header">
      <h3 class="display-4" style="color: antiquewhite; font-weight: 500; font-size: xx-large;"> {{i.title}} </h3>
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p style="color: antiquewhite;">{{i.desc}}</p>
          <!-- <p class="lead">
            <a class="btn btn-primary btn-lg" href="#" role="button">Like</a>
          </p> -->
          <footer class="blockquote-footer" style="color: antiquewhite;">Written by- <cite title="Source Title" style="color: antiquewhite;">{{i.author}}</cite></footer>
        </blockquote>
      </div>
    </div>
    <br>
    <br>
  {% endfor %}
</div>
{% endblock content %}

blogapplication/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}



<div class="col-sm-10 text-center">
    <h3 class="text-white  text-center" style="margin-top: 80px;" >LOGIN </h3>
    <form method="post"  novalidate>
        {% csrf_token %}
        {% for fm in Form %}
        <div class="row mb-3">
            <label for="inputEmail3" class="col-sm-2 col-form-label">{{fm.label_tag}} </label>
            <div class="col-sm-10">
                {{fm}}
            </div>
        </div>
            <p style="color: red;" >  {{fm.errors | striptags}} </p> 
        {% endfor %}
        <input type="submit" value="Login" class="btn btn-dark form-control"><br>
        <label for="one" class="col-sm-2 col-form-label">New User ?</label>
        <a href="{% url 'signup' %}" style="text-decoration: none;"  class="btn btn-dark form-control"> REGISTER HERE </a> 
    </form>
</div>

























{% endblock content %}

blogapplication/templates/blog/navbar.html
<nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">My Blogs</a>
      <!-- <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">My Blogs</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 text-center">
            <form class="d-flex mt-3" role="search">
              <input class="form-control me-2" type="search" placeholder="Can Not Search Now" aria-label="Search">
              <button class="btn btn-success" type="submit">Search</button>
            </form>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Blogs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Signup</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>
 

blogapplication/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}



<div class="col-sm-10 text-center">
    <h3 class="text-white  text-center" style="margin-top: 80px;" >Sign Up </h3>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for fm in Form %}
        <div class="row mb-3">
            <label for="inputEmail3" class="col-sm-2 col-form-label">{{fm.label_tag}} </label>
            <div class="col-sm-10">{{fm}} </div></div>
                          <p style="color: red;" >  {{fm.errors | striptags}} </p> 
        
        {% endfor %}
        <input type="submit" value="SIGN UP" class="btn btn-dark form-control"/> <br>
        <label for="one" class="col-sm-2 col-form-label">Already Registered ?</label>
         <a href="{% url 'login' %}" style="text-decoration: none;"  class="btn btn-dark form-control" id="one"> LOGIN HERE </a> 
    </form>
</div>

























{% endblock content %}

blogapplication/templates/blog/update.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}


<div class="col-sm-10">
    <h3 class="text-white my-5" > Dashboard /Update Post</h3>
    <form method="post" novalidate>
        {% csrf_token %}
        {% for fm in Form %}
        <div class="row mb-3">
            <label for="inputEmail3" class="col-sm-2 col-form-label">{{fm.label_tag}} </label>
            <div class="col-sm-10">{{fm}} </div></div>
                          <p style="color: red;" >  {{fm.errors | striptags}} </p> 
        
        {% endfor %}
        <input type="submit" value="UPDATE" class="btn btn-dark form-control"/> <br>
    </form>
</div>
{% endblock content %}

blogapplication/templates/blog/welcome.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}



<div class="col-sm-10 text-center">
    <h3 class="text-white  text-center" style="margin-top: 60px;" >Welcome to MyBlogs.com !</h3>
    
    <div class="card">
        <div class="card-body">
          <h5 class="card-title" style="color: antiquewhite;">REGISTER </h5>
          <hr style="color: antiquewhite;">
          <p class="card-text" style="color: antiquewhite;">At MyBlogs, we believe in the power of expression, creativity, and sharing ideas. Whether you're a seasoned writer, a budding poet, an amateur photographer, or someone with a passion to share stories, MyBlogs provides the perfect platform for you to unleash your creativity and connect with like-minded individuals from around the globe.</p>
          <a href="{% url 'signup' %}" class="btn btn-primary">Signup</a>
        </div>
      </div>
      <br>
      <br>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title" style="color: antiquewhite;"> READ/WRITE BLOGS  </h5>
          <hr style="color: antiquewhite;">
          <p class="card-text" style="color: antiquewhite;">Explore a diverse range of topics, from lifestyle and travel to technology and philosophy. Dive into captivating narratives, insightful reflections, and thought-provoking discussions curated by our vibrant community of bloggers</p>
          <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
        </div>
      </div>
    <!-- <div class="card text-center text-white">
        <div class="card-header">
          <h5 class="card-title font-weight-bold">
          Blog Title
          </h5>
        </div>
        <div class="card-body">
          <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="btn btn-primary">LIKE</a>
        </div>
        <div class=" text-white card-footer text-body-secondary " >
          2 days ago
        </div>
      </div> -->
</div>

























{% endblock content %}